sudo: false

language: node_js
node_js:
  - 9

before_install:
  - npm install codecov.io coveralls

install:
  - npm i -g npm@5.7.1
  - npm ci

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master

notifications:
  email: change
